### ISSUE TITLE
No known prefix exception

### ISSUE THREAD

**Issue by zalky** [larsgrefer/dart-sass-java#104]
Hi and thanks for putting together this great library!

I've been testing out the Webjars/Classpath importers with success until I recently stumbled into the following exception:

```
Error: java.lang.IllegalStateException: jar:file:/Users/user/.m2/repository/org/webjars/bower/bootstrap/4.1.1/bootstrap-4.1.1.jar!/META-INF/resources/webjars/bootstrap/4.1.1/scss/functions has no known prefix
   at de.larsgrefer.sass.embedded.importer.CustomUrlImporter.getRelativePart(CustomUrlImporter.java:90)
   at de.larsgrefer.sass.embedded.importer.CustomUrlImporter.canonicalize(CustomUrlImporter.java:35)
   at system.sass.proxy$de.larsgrefer.sass.embedded.importer.ClasspathImporter$ff19274a.canonicalize(Unknown Source)                             
   at de.larsgrefer.sass.embedded.importer.AutoCanonicalizingImporter.canonicalize(AutoCanonicalizingImporter.java:20)                           
   at de.larsgrefer.sass.embedded.SassCompiler.handleCanonicalizeRequest(SassCompiler.java:332)
   at de.larsgrefer.sass.embedded.SassCompiler.exec(SassCompiler.java:261)
   at de.larsgrefer.sass.embedded.SassCompiler.execCompileRequest(SassCompiler.java:225)
   at de.larsgrefer.sass.embedded.SassCompiler.compileFile(SassCompiler.java:215)
   at de.larsgrefer.sass.embedded.SassCompiler.compileFile(SassCompiler.java:206)
   at de.larsgrefer.sass.embedded.SassCompiler.compile(SassCompiler.java:140)
```

In this particular case bootstrap is actually a transitive import in a sass file in _another jar_, such that the bootstrap webjar and the other jar do not share a prefix:

```
"jar:file:/Users/user/.m2/repository/some/other/jar/file/0.0.1/file.jar!/css/main.scss"
```
which imports

```
"jar:file:/Users/user/.m2/repository/org/webjars/bower/bootstrap/4.1.1/bootstrap-4.1.1.jar!/META-INF/resources/webjars/bootstrap/4.1.1/scss/functions.scss"
```
I'm not sure I fully understand the code, but I wonder if it just can't past [the following conditional](https://github.com/larsgrefer/dart-sass-java/blob/aa4a8b98053ec19504a42874b92499e7cf2d1ec5/sass-embedded-host/src/main/java/de/larsgrefer/sass/embedded/importer/CustomUrlImporter.java#L34-L40)? Maybe I've misunderstood but it would seem that that would only ever collect a single prefix, and then fail on the next distinct prefix as imports are being processed.

Let me know if this makes any sense or if you require any further information to make a determination.

Thanks!

**Comment by larsgrefer** [comment]
It would be really helpful if you could provide an MVCE project which reproduces your error which I can try out locally.

What exactly are the contents of `jar:file:/Users/user/.m2/repository/some/other/jar/file/0.0.1/file.jar!/css/main.scss`?

**Comment by zalky** [comment]
Thanks for the quick response! Also, apologies, I forgot to include the sass import error message after the stacktrace:

```
   ╷
 8 │ @import "functions";
   │         ^^^^^^^^^^^
   ╵
   scss/bootstrap.scss 8:9  @import
   css/main.scss 2:9        @import
   src/scss/main.scss 1:9   root stylesheet
```

It might take me a bit to carve out a MVCE project. In the meantime, I pared down the `main.scss` to a single `@import "scss/bootstrap;"` statement and I still get the same exception.

The basic setup:

1. A root stylesheet `file.scss` resource that gets passed to the compiler:

   ```
   @import "css/main";
   ```
2. A jar containing a `css/main.scss` file that has only a single import statement:

   ```
   @import "scss/bootstrap";
   ```
3. The bootstrap webjar as a dependency on the classpath. 

I can also confirm the full `main.scss` compiles if it is not in a jar, but just a regular resource file on the classpath.

**Comment by larsgrefer** [comment]
interesting setup, but I have an Idea of what happens here:

1. The root stylesheet calls for `css/main`
2. The classpath importer resolves `css/main` to `jar:file:/Users/user/.m2/repository/some/other/jar/file/0.0.1/file.jar!/css/main.scss`
3. `main.scss` calls for `scss/bootstrap`
4. the sass compiler asks the classpath importer to canonicalize `scss/bootstrap` which fails with the above error (since it can't resolve it)

**Comment by larsgrefer** [comment]
I've tried to build a reproducing test here, but its working: https://github.com/larsgrefer/dart-sass-java/blob/8f9ed54484c4fbf94bc755d1251b35a381907735/sass-embedded-host/src/test/java/de/larsgrefer/sass/embedded/Issue104Test.java

**Comment by zalky** [comment]
Thanks for putting those tests together, they were very instructive, and helped me resolve the issue!

I was working on a Clojure wrapper for the embedded host to replace an older deprecated wrapper around Jsass. The older Jsass wrapper does some added canonicalization on webjar `@import` URLs and I was trying to reproduce this, but I did it in the wrong place.

I was trying to extend the `canonicalizeUrl` method of WebjarsImporter, but I think this was the wrong place to do it. [In this conditional](https://github.com/larsgrefer/dart-sass-java/blob/8f9ed54484c4fbf94bc755d1251b35a381907735/sass-embedded-host/src/main/java/de/larsgrefer/sass/embedded/importer/CustomUrlImporter.java#L55-L60) `url` and `urlString` would always be inconsistent, because of the mapping. Therefore the prefix would not be added to the `usedPrefixes`, and then the next `getRelativePart` would fail. I unfortunately also didn't happen see the logging on L59, due to the SLF4J config in the parent project.

Instead, I tried doing the mapping by extending `canonicalize` and calling super, that way the parent context of `canonicalize` would always see a consistent url. The files now successfully compile with the additional canonicalization!

I don't know if that clear. TLDR; it seems to be working now 😄
