### ISSUE TITLE
Unable to check for rosetta

### ISSUE THREAD

**Issue by ia3andy** [larsgrefer/dart-sass-java#382]
I get this log (on macos), the check should be more resilient.

```
2023-10-12 09:22:15,176 INFO  [de.lar.sas.emb.bun.BundledCompilerFactory] (build-4) Unable to check for rosetta: java.lang.StringIndexOutOfBoundsException: offset 0, count -1, length 16
	at java.base/java.lang.String.checkBoundsOffCount(String.java:4589)
	at java.base/java.lang.String.<init>(String.java:523)
	at de.larsgrefer.sass.embedded.bundled.BundledCompilerFactory.isRunningOnRosetta2(BundledCompilerFactory.java:105)
	at de.larsgrefer.sass.embedded.bundled.BundledCompilerFactory.getBundledCompilerDistPath(BundledCompilerFactory.java:72)
	at de.larsgrefer.sass.embedded.bundled.BundledCompilerFactory.extractBundled(BundledCompilerFactory.java:31)
	at de.larsgrefer.sass.embedded.bundled.BundledCompilerFactory.getBundledDartExec(BundledCompilerFactory.java:25)
	at de.larsgrefer.sass.embedded.bundled.BundledCompilerFactory.call(BundledCompilerFactory.java:119)
	at de.larsgrefer.sass.embedded.bundled.BundledCompilerFactory.call(BundledCompilerFactory.java:14)
	at de.larsgrefer.sass.embedded.connection.ConnectionFactory.bundled(ConnectionFactory.java:40)
	at de.larsgrefer.sass.embedded.SassCompilerFactory.bundled(SassCompilerFactory.java:25)
	at io.quarkiverse.web.bundler.sass.SassBuildTimeCompiler.convertScss(SassBuildTimeCompiler.java:47)
	at io.quarkiverse.web.bundler.deployment.WebBundlerProcessor.convertToScss(WebBundlerProcessor.java:276)
	at io.quarkiverse.web.bundler.deployment.WebBundlerProcessor.lambda$bundle$2(WebBundlerProcessor.java:230)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.quarkiverse.web.bundler.deployment.WebBundlerProcessor.bundle(WebBundlerProcessor.java:230)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	```

**Comment by ia3andy** [comment]
I didn't have this log with the previous implementation:
```
/**
     * Check if we are running on an Intel x86_64 JDK emulated by Rosetta2 on an ARM mac.
     */
    private static boolean isRunningOnRosetta2() {
        try {
            Process sysctl = Runtime.getRuntime().exec("sysctl -in sysctl.proc_translated");
            ByteString stdOut;
            try (InputStream in = sysctl.getInputStream()) {
                stdOut = ByteString.readFrom(in);
            }
            if (sysctl.exitValue() == 0 && stdOut.toStringUtf8().equals("1\n")) {
                return true;
            }
        } catch (Exception e) {
            log.info("Unable to check for rosetta", e);
        }
        return false;
    }
    ```

**Comment by ia3andy** [comment]
It was working fine on 3.0.0-m1 (-m2 is not working because of a missing dependency)

**Comment by ia3andy** [comment]
FYI I am using this library in https://github.com/quarkiverse/quarkus-web-bundler/

**Comment by larsgrefer** [comment]
After moving the bundled compilers into a separate jar in response to #322 the extraction logic does not have ByteString availabe on its classpath. Thats why the implementation has been changed.

Do you have an M1/M2 mac or is it an intel one?
Whats the output of `sysctl -in sysctl.proc_translated` on your commandline?

**Comment by larsgrefer** [comment]
Update: It also happens on ci: https://github.com/larsgrefer/dart-sass-java/actions/runs/6473813914/job/17577335074#step:7:164

**Comment by ia3andy** [comment]
> sysctl -in sysctl.proc_translated

<img width="700" alt="image" src="https://github.com/larsgrefer/dart-sass-java/assets/2223984/5833d262-ad94-4b96-8608-4d79686ba415">

The output is empty.

It's a mac intel

**Comment by ia3andy** [comment]
Cheers!

**Comment by ia3andy** [comment]
And thanks for the lib :)

**Comment by larsgrefer** [comment]
Just for clarification: The issue only affects the logging output while the acutal compilation works as intended, correct?
